### PR TITLE
[1.21-fabric] Energy Style Option

### PR DESCRIPTION
**Pull request by Stein-N**
A Little option to change the appearance of the Energy inside the tooltip.

Normal and Default appearance:
energy_progress_default

Minimal opt-in appearance:
energy_progress_minimal

### CODE REVIEW

**Comment by Snownee** [comment]
I don't think it's fit to be called “minimal”. It's just another style of displaying

**Comment by Stein-N** [comment]
Would be 'Plain/Only Text' fit better for you?
Or i could try to change it the way that instead of the progress bar a simple energy symbol is rendered?

**Comment by Stein-N** [comment]
Hey i added the DisplayStyle enum so that the player can switch between 3 styles:

Progressbar -> is also the default when no specific style for an enum is defined:
Text -> like u can see above
Symbol:
energy_progress_symbole

**Comment by Snownee** [comment]
It's looks good. Who made the icon?

**Comment by Stein-N** [comment]
Made the icon by myself for a project that gets dropped quickly.

Should i apply those Style options also to the FluidStorage, for that i would use the normal bucket texture?
fluid_storage_symbol
fluid_storage_text

**Comment by Snownee** [comment]
Okay. You can only edit this branch. I will change some details before porting it

**Comment by Stein-N** [comment]
Ok finished with the FluidStorageProvider, this is something that need to be better implemented but would work for now.

The DisplayStyle should be received before init the text Component and when it is not the Progressbar style it always should use the fluid_2 text.

```java
Component text;
DisplayStyle style = config.getEnum(JadeIds.UNIVERSAL_FLUID_STORAGE_STYLE);

if (view.overrideText != null) {
	text = view.overrideText;
} else if (view.fluidName == null) {
	text = Component.literal(view.current);
} else if (accessor.showDetails() || style != DisplayStyle.PROGRESSBAR) {
	text = Component.translatable(
		"jade.fluid2",
		IDisplayHelper.get().stripColor(view.fluidName).withStyle(ChatFormatting.WHITE),
		Component.literal(view.current).withStyle(ChatFormatting.WHITE),
		view.max).withStyle(ChatFormatting.GRAY);
} else {
	text = Component.translatable("jade.fluid", IDisplayHelper.get().stripColor(view.fluidName), view.current);
}```

**Comment by Snownee** [comment]
Please render the bucket item instead of using sprite

**Comment by Stein-N** [comment]
Sry overlooked that method.

**Pull request merged**
