### PR TITLE
Update lang/pt-br

### PR DESCRIPTION
**Pull request by FITFC**

### CODE REVIEW

**Comment by Snownee** [comment]
Hello, could you please translate these entries: "gui.jade.disabled_by_mods", "gui.jade.server_features", "gui.jade.server_features.tip". All the "server feature" and "server features" need to be translated.

**Comment by Snownee** [comment]
@FITFC

**Comment by FITFC** [comment]
Sorry, I was travelling, I'll check that out as soon as possible! you can count on me

**Comment by FITFC** [comment]
I already made the corrections, took advantage and made some revisions.

**Comment by Snownee** [comment]
Thank you!

**Pull request merged**
